### PR TITLE
Terraform Plugin SDK v2 Upgrade

### PR DESCRIPTION
**Pull request by w9n**
followed this doc:
https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide

### CODE REVIEW

**Comment by tehcyx** [comment]
Hi,

Thanks for looking into this. Have you run the tests via `make testacc` ? I've checked out your changes via GitHub Codespaces and running the tests actually fails for me with a panic:
```
$ make testacc
./before-commit.sh testacc

USER:  + codespace
PATH:  + /usr/local/cargo/bin:/usr/local/sdkman/candidates/java/current/bin:/home/codespace/.rbenv/shims:/usr/local/go/bin:/vscode/bin/linux-x64/f80445acd5a3dadef24aa209168452a3d97cc326/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/codespace/.nvm/current/bin:/home/codespace/.npm-global/bin:/home/codespace/.dotnet:/home/codespace/.dotnet/tools:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/java/current/bin:/opt/maven/lts:/usr/local/cargo/bin:/usr/local/go/bin:/go/bin:/usr/local/py-utils/bin:/opt/conda/condabin:/opt/oryx:/opt/nodejs/lts/bin:/opt/dotnet/lts:/opt/python/latest/bin:/opt/php/lts/bin:/opt/php-composer:/opt/yarn/stable/bin:/opt/hugo/lts::/opt/java/lts/bin:/opt/maven/lts/bin:/opt/ruby/lts/bin:/home/codespace/.local/bin:/usr/local/rvm/bin
GOPATH: + /go

go: downloading github.com/hashicorp/terraform-plugin-sdk/v2 v2.10.1
go: downloading github.com/imdario/mergo v0.3.12
go: downloading golang.org/x/crypto v0.0.0-20210616213533-5ff15b29337e
go: downloading github.com/apparentlymart/go-cidr v1.0.1
go: downloading github.com/hashicorp/go-hclog v0.16.1
go: downloading github.com/hashicorp/go-plugin v1.4.1
go: downloading github.com/hashicorp/terraform-plugin-go v0.5.0
go: downloading github.com/mitchellh/go-testing-interface v1.14.1
go: downloading google.golang.org/grpc v1.32.0
go: downloading github.com/google/go-cmp v0.5.6
go: downloading github.com/hashicorp/go-cty v1.4.1-0.20200414143053-d3edf31b6320
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/mitchellh/copystructure v1.2.0
go: downloading github.com/hashicorp/terraform-exec v0.15.0
go: downloading github.com/hashicorp/terraform-json v0.13.0
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading github.com/mitchellh/reflectwalk v1.0.2
go: downloading github.com/stretchr/testify v1.7.0
go: downloading golang.org/x/net v0.0.0-20210326060303-6b1517762897
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading github.com/hashicorp/terraform-plugin-log v0.2.0
go: downloading github.com/hashicorp/terraform-registry-address v0.0.0-20210412075316-9b2996cce896
go: downloading golang.org/x/term v0.0.0-20201126162022-7de9c90e9dd1
go: downloading golang.org/x/text v0.3.5
go: downloading github.com/vmihailenco/msgpack v4.0.4+incompatible
go: downloading github.com/hashicorp/hcl/v2 v2.3.0
go: downloading github.com/hashicorp/go-version v1.3.0
go: downloading github.com/nsf/jsondiff v0.0.0-20200515183724-f29ed568f4ce
go: downloading github.com/zclconf/go-cty v1.9.1
go: downloading github.com/hashicorp/hc-install v0.3.1
go: downloading gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
go: downloading golang.org/x/sys v0.0.0-20210615035016-665e8c7367d1
go: downloading google.golang.org/genproto v0.0.0-20200711021454-869866162049
go: downloading github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
go: downloading google.golang.org/appengine v1.6.6
go: downloading github.com/kr/pretty v0.2.1
go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
go: downloading github.com/hashicorp/go-getter v1.5.3
go: downloading github.com/apparentlymart/go-textseg/v13 v13.0.0
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/go-git/go-git/v5 v5.4.2
go: downloading cloud.google.com/go v0.61.0
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading github.com/aws/aws-sdk-go v1.25.3
go: downloading github.com/klauspost/compress v1.11.2
go: downloading github.com/ulikunitz/xz v0.5.8
go: downloading google.golang.org/api v0.29.0
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20210428141323-04723f9f07d7
go: downloading github.com/go-git/go-billy/v5 v5.3.1
go: downloading github.com/sergi/go-diff v1.2.0
go: downloading github.com/emirpasic/gods v1.12.0
go: downloading github.com/acomagu/bufpipe v1.0.3
go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: downloading golang.org/x/tools v0.0.0-20200713011307-fd294ab11aed
go: downloading go.opencensus.io v0.22.4
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: downloading github.com/go-git/gcfg v1.5.0
go: downloading github.com/kevinburke/ssh_config v0.0.0-20201106050909-4977a11b4351
go: downloading github.com/xanzy/ssh-agent v0.3.0
go: downloading gopkg.in/warnings.v0 v0.1.2
go: downloading github.com/Microsoft/go-winio v0.4.16
go: downloading golang.org/x/mod v0.3.0
√ go mod tidy
√ go build (dev)
? go mod verify
√ go mod verify
? go test
?       github.com/kyma-incubator/terraform-provider-kind       [no test files]
ok      github.com/kyma-incubator/terraform-provider-kind/kind  0.012s
√ go test
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccCluster
=== PAUSE TestAccCluster
=== RUN   TestAccClusterConfigBase
=== PAUSE TestAccClusterConfigBase
=== RUN   TestAccClusterConfigNodes
=== PAUSE TestAccClusterConfigNodes
=== RUN   TestAccClusterContainerdPatches
=== PAUSE TestAccClusterContainerdPatches
=== RUN   TestAccContainerdPatchFormatOnlyChangeIsNoop
=== PAUSE TestAccContainerdPatchFormatOnlyChangeIsNoop
=== RUN   TestNormalizeTomlString
=== RUN   TestNormalizeTomlString/WellFormattedIsReturnedAsIs
=== RUN   TestNormalizeTomlString/MalformedInputResultsInErrorAndReturnsInput
=== RUN   TestNormalizeTomlString/UnformattedInputIsFormatted
--- PASS: TestNormalizeTomlString (0.00s)
    --- PASS: TestNormalizeTomlString/WellFormattedIsReturnedAsIs (0.00s)
    --- PASS: TestNormalizeTomlString/MalformedInputResultsInErrorAndReturnsInput (0.00s)
    --- PASS: TestNormalizeTomlString/UnformattedInputIsFormatted (0.00s)
=== RUN   TestStringIsValidToml
=== RUN   TestStringIsValidToml/PassingNonStringIsAnError
=== RUN   TestStringIsValidToml/ValidTomlIsValid
=== RUN   TestStringIsValidToml/NilIsInvalid
=== RUN   TestStringIsValidToml/EmptyStringIsValid
=== RUN   TestStringIsValidToml/InvalidTomlIsInvalid
--- PASS: TestStringIsValidToml (0.00s)
    --- PASS: TestStringIsValidToml/PassingNonStringIsAnError (0.00s)
    --- PASS: TestStringIsValidToml/ValidTomlIsValid (0.00s)
    --- PASS: TestStringIsValidToml/NilIsInvalid (0.00s)
    --- PASS: TestStringIsValidToml/EmptyStringIsValid (0.00s)
    --- PASS: TestStringIsValidToml/InvalidTomlIsInvalid (0.00s)
=== CONT  TestAccCluster
Creating cluster "tf-acc-cluster-test-8464690816383475240" ...
 • Ensuring node image (kindest/node:v1.21.1) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦 
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✓ Starting control-plane 🕹️
 • Installing CNI 🔌  ...
 ✓ Installing CNI 🔌
 • Installing StorageClass 💾  ...
 ✓ Installing StorageClass 💾
panic: Invalid address to set: []string{"completed"}

goroutine 298 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc002e72180, 0x111be3d, 0x9, 0xf755a0, 0x187c108, 0x0, 0x0)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:230 +0x371
github.com/kyma-incubator/terraform-provider-kind/kind.resourceKindClusterRead(0xc002e72180, 0x0, 0x0, 0x2, 0x2)
        /workspaces/terraform-provider-kind/kind/resource_cluster.go:182 +0x765
github.com/kyma-incubator/terraform-provider-kind/kind.resourceKindClusterCreate(0xc002e72180, 0x0, 0x0, 0x0, 0xffffffffffffffff)
        /workspaces/terraform-provider-kind/kind/resource_cluster.go:139 +0x4f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000426460, 0x12894e8, 0xc002dfdb80, 0xc002e72180, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000426460, 0x12894e8, 0xc002dfdb80, 0xc002e64750, 0xc002e72000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000014c48, 0x12894e8, 0xc002dfdb80, 0xc002e62410, 0x1123028, 0x12, 0x0)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002badf80, 0x1289590, 0xc002dfdb80, 0xc002e3d1f0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x465
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10c5920, 0xc002badf80, 0x1289590, 0xc002e54f60, 0xc002e46840, 0x0, 0x1289590, 0xc002e54f60, 0xc002a12780, 0x242)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc002a21a40, 0x12941b8, 0xc002bfb200, 0xc0000ff000, 0xc002bffda0, 0x18ec8a0, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc002a21a40, 0x12941b8, 0xc002bfb200, 0xc0000ff000, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001c46c0, 0xc002a21a40, 0x12941b8, 0xc002bfb200, 0xc0000ff000)
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
FAIL    github.com/kyma-incubator/terraform-provider-kind/kind  62.801s
FAIL
√ go fmt
√ go vet ./kind/... 
```

Do you see that on your end as well?

**Comment by w9n** [comment]
oh, didnt notice that. It was caused by a missing ressource schema according to [stricter error handling](https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide#louder-helper-schema-resourcedata-set-errors-in-testing
). fixed now.

This license just feels morally wrong:

> Moral Rights. To the fullest extent permitted under applicable law, you hereby waive, and agree not to assert, all of your “moral rights” in or relating to your Contributions for the benefit of SAP, its assigns, and their respective direct and indirect sublicensees.

**Comment by tehcyx** [comment]
> oh, didnt notice that. It was caused by a missing ressource schema according to [stricter error handling](https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide#louder-helper-schema-resourcedata-set-errors-in-testing). fixed now.
> 
> This license just feels morally wrong:
> 
> > Moral Rights. To the fullest extent permitted under applicable law, you hereby waive, and agree not to assert, all of your “moral rights” in or relating to your Contributions for the benefit of SAP, its assigns, and their respective direct and indirect sublicensees.

I won't be able to merge this without the license being accepted.

**Comment by w9n** [comment]
agreed - ive gotten a better understanding of the english term "moral rights" [here](https://cyber.harvard.edu/property/library/moralprimer.html).

**Review by tehcyx — APPROVED** [review]

**Pull request merged**
